# Numpy Data Structures

Numpy data structure examples based on Chap 4 of 'Python for Finance'

In [1]:
v=[0.5, 0.75, 1.0, 1.5, 2.0]

In [2]:
m=[v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v1 = [0.5, 1.5]
v2 = [1,2]
m=[v1,v2]
c=[m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [6]:
c[1][1][0]

1

In [9]:
v=[0.5, 0.75, 1.0, 1.5, 2.0]
m=[v,v,v] # This is reference copying. Caution!!
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [11]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [12]:
from copy import deepcopy
v=[0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v)]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [13]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
import numpy as np

In [16]:
a = np.array([0,0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [17]:
a[:2]

array([ 0. ,  0.5])

In [18]:
a.sum()

5.0

In [19]:
a.std()

0.70710678118654757

In [20]:
a.cumsum()

array([ 0. ,  0.5,  1.5,  3. ,  5. ])

In [21]:
a*2

array([ 0.,  1.,  2.,  3.,  4.])

In [22]:
a**2

array([ 0.  ,  0.25,  1.  ,  2.25,  4.  ])

In [23]:
np.sqrt(a)

array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

In [24]:
b = np.array([a, a*2])
b

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 0. ,  1. ,  2. ,  3. ,  4. ]])

In [25]:
b[0]

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [26]:
b[0,2]

1.0

In [27]:
b[0][2]

1.0

In [28]:
b.sum()

15.0

In [29]:
b.sum(axis=0)

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [30]:
b.sum(axis=1)

array([  5.,  10.])

In [31]:
c= np.zeros((2,3,4), dtype='i', order='C')
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [33]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]],

       [[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]]], dtype=float128)

In [34]:
import random
I=5000

In [35]:
%time mat = [[random.gauss(0,1) for j in range(I) for i in range(I)]]

CPU times: user 25 s, sys: 351 ms, total: 25.3 s
Wall time: 25.3 s


In [41]:
%time reduce(lambda x, y: x+y, [reduce(lambda x, y: x+y, row) for row in mat])

NameError: name 'reduce' is not defined

In [42]:
%time mat = np.random.standard_normal((I,I))

CPU times: user 1.43 s, sys: 150 ms, total: 1.58 s
Wall time: 1.58 s


In [43]:
%time mat.sum()

CPU times: user 19.1 ms, sys: 1.57 ms, total: 20.7 ms
Wall time: 18.9 ms


7160.9470736339799

In [4]:
dt=np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4',2)])
s=np.array([('Smith', 45, 1.83, (0,1)), ('Jones', 53, 1.73, (2,2))], dtype=dt)
s

array([(b'Smith', 45,  1.83000004, [0, 1]),
       (b'Jones', 53,  1.73000002, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [5]:
s['Name']

array([b'Smith', b'Jones'],
      dtype='|S10')

In [6]:
s['Height'].mean()

1.78

In [7]:
s[1]['Age']

53

In [9]:
r=np.random.standard_normal((4,3))
s=np.random.standard_normal((4,3))

In [10]:
r+s

array([[ 4.64545965,  0.64075837, -1.02625744],
       [ 2.04708667, -2.41297443,  0.27058615],
       [-0.56112795, -1.97300553,  1.62207588],
       [ 0.76677116, -0.3877779 ,  1.69354897]])

In [11]:
2*r+3

array([[ 8.56275051,  4.91815989, -0.24801868],
       [ 4.70272524,  0.63023593,  4.56826109],
       [ 2.90417763,  3.6970584 ,  1.44085514],
       [ 5.94730168,  2.53115178,  5.62374327]])

In [12]:
s=np.random.standard_normal(3)
r+s

array([[ 2.01740258,  0.20939727, -0.53109947],
       [ 0.08738995, -1.93456471,  1.87704041],
       [-0.81188385, -0.40115348,  0.31333744],
       [ 0.70967817, -0.98410679,  2.4047815 ]])

In [13]:
s=np.random.standard_normal(4)
r+s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [14]:
r.transpose()+s

array([[ 1.65948471, -0.15866312, -0.5482863 ,  1.183506  ],
       [-0.1628106 , -2.19490777, -0.15184592, -0.52456894],
       [-2.74589988, -0.2258952 , -1.27994754,  1.0217268 ]])

In [15]:
np.shape(r.T)

(3, 4)

In [16]:
def f(x):
    return 3 * x + 5

In [17]:
f(0.5)

6.5

In [18]:
f(r)

array([[ 13.34412576,   7.87723983,   0.12797198],
       [  7.55408785,   1.4453539 ,   7.35239163],
       [  4.85626645,   6.0455876 ,   2.66128272],
       [  9.42095252,   4.29672767,   8.9356149 ]])

In [19]:
np.sin(r)

array([[ 0.35247769,  0.81866355, -0.99858452],
       [ 0.75217901, -0.92645467,  0.70620987],
       [-0.04789286,  0.34151581, -0.70297539],
       [ 0.99528509, -0.23228289,  0.96666586]])

In [20]:
np.sin(np.pi)

1.2246467991473532e-16

In [25]:
x = np.random.standard_normal((5,10000000))
y = 2 * x + 3
C = np.array((x,y), order='C')
F = np.array((x,y), order='F')
x = 0.0; y = 0.0

In [26]:
C[:2].round(2)

array([[[-0.38, -1.36, -0.24, ..., -0.03, -0.46,  0.14],
        [ 1.9 ,  0.29,  0.28, ...,  0.23, -0.9 , -0.28],
        [-0.74, -0.55, -0.19, ...,  0.09, -0.3 , -0.55],
        [-1.3 ,  1.89,  0.83, ...,  0.62, -1.38,  1.13],
        [-0.73, -0.36,  0.45, ...,  0.62, -2.18, -0.08]],

       [[ 2.24,  0.28,  2.53, ...,  2.94,  2.09,  3.28],
        [ 6.79,  3.58,  3.56, ...,  3.45,  1.2 ,  2.45],
        [ 1.52,  1.89,  2.62, ...,  3.18,  2.4 ,  1.89],
        [ 0.4 ,  6.78,  4.66, ...,  4.24,  0.24,  5.27],
        [ 1.55,  2.27,  3.9 , ...,  4.23, -1.37,  2.84]]])

In [27]:
%timeit C.sum()

61.6 ms ± 2.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
%timeit F.sum()

60.4 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
%timeit C[0].sum(axis=0)

88.8 ms ± 1.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
%timeit C[0].sum(axis=1)

31.4 ms ± 2.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
%timeit F.sum(axis=0)

1.25 s ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%timeit F.sum(axis=1)

2.62 s ± 29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
F=0.0; C=0.0