# Numpy Data Structures

Numpy data structure examples based on Chap 4 of 'Python for Finance'

In [1]:
v=[0.5, 0.75, 1.0, 1.5, 2.0]

In [2]:
m=[v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v1 = [0.5, 1.5]
v2 = [1,2]
m=[v1,v2]
c=[m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [6]:
c[1][1][0]

1

In [9]:
v=[0.5, 0.75, 1.0, 1.5, 2.0]
m=[v,v,v] # This is reference copying. Caution!!
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [11]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [12]:
from copy import deepcopy
v=[0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v)]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [13]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [14]:
import numpy as np

In [16]:
a = np.array([0,0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [17]:
a[:2]

array([ 0. ,  0.5])

In [18]:
a.sum()

5.0

In [19]:
a.std()

0.70710678118654757

In [20]:
a.cumsum()

array([ 0. ,  0.5,  1.5,  3. ,  5. ])

In [21]:
a*2

array([ 0.,  1.,  2.,  3.,  4.])

In [22]:
a**2

array([ 0.  ,  0.25,  1.  ,  2.25,  4.  ])

In [23]:
np.sqrt(a)

array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

In [24]:
b = np.array([a, a*2])
b

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 0. ,  1. ,  2. ,  3. ,  4. ]])

In [25]:
b[0]

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [26]:
b[0,2]

1.0

In [27]:
b[0][2]

1.0

In [28]:
b.sum()

15.0

In [29]:
b.sum(axis=0)

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [30]:
b.sum(axis=1)

array([  5.,  10.])

In [31]:
c= np.zeros((2,3,4), dtype='i', order='C')
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [33]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]],

       [[ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0],
        [ 1.0,  1.0,  1.0,  1.0]]], dtype=float128)

In [34]:
import random
I=5000

In [35]:
%time mat = [[random.gauss(0,1) for j in range(I) for i in range(I)]]

CPU times: user 25 s, sys: 351 ms, total: 25.3 s
Wall time: 25.3 s


In [41]:
%time reduce(lambda x, y: x+y, [reduce(lambda x, y: x+y, row) for row in mat])

NameError: name 'reduce' is not defined

In [42]:
%time mat = np.random.standard_normal((I,I))

CPU times: user 1.43 s, sys: 150 ms, total: 1.58 s
Wall time: 1.58 s


In [43]:
%time mat.sum()

CPU times: user 19.1 ms, sys: 1.57 ms, total: 20.7 ms
Wall time: 18.9 ms


7160.9470736339799